### ISSUE TITLE
Exposé Nils 

### ISSUE THREAD

**Issue by NMA93** [logrinto/IAD2017.diplom#1]
Datum: 30.03.2020

**Schule für Gestaltung Zürich** <br>
Bildungsgang Interaction Design HF <br>
Dipl. Gestalter/-in HF, Kommunikationsdesign mit Vertiefungsrichtung Interaction Design

# Exposé Abschlussarbeit HFIAD17

## Mentoring durch
 
**Jürg Schaeppi**<br>
Senior UX-Designer<br>
Publicis Schweiz <br>

## Vorgelegt von
 
**Nils Mäder**<br>
Zürichstrasse 8<br>
8610 Uster<br>
mail@nilsmaeder.ch<br>

## Problemstellung
Der Accessibility Developer Guide ist ein bewährtes Instrument für Entwickler um sich über den barrierefreien Aufbau von Websites zu informieren. Für Designer von User Interfaces lassen sich ebenfalls Informationen finden, jedoch sind die nicht annähernd so ausführlich beschrieben wie für Developer.

Für User Interface Designer gibt es diverse Vorgaben die beachtet werden müssen, jedoch gibt es keine Seite, die diese in der Qualität des Developer Guide sammelt. Für Designer sind die Informationen in diversen unterschiedlichen Blogs untergebracht oder nicht ansprechend und strukturiert aufbereitet. Siehe folgendes Beispiel: Web Content Accessibility Guidelines (WCAG) 2.0.

## Ziel dieser Arbeit
Die Erarbeitung einer interaktiven Seite, die Wissen zum Thema Barrierefreies Design vermittelt und in Zukunft als Tool von UI-Designer weltweit genutzt werden kann. Ein wichtiger Bestandteil dieser Arbeit ist, dass das Endresultat weiterlebt und über die Aufgabenstellung «Abschlussarbeit» hinaus einen Nutzen hat. Die Arbeit sollte am Ende nicht als abgeschlossen betrachtet werden (v1.0).

## Persönliches Interesse
Als UX-Designer sehe ich es als meine Pflicht, digitale Medien, soweit es möglich ist, für alle Menschen zugänglich zu gestalten. Accessibility beginnt bei der Konzeption, geht über das Design und die Entwicklung hinaus und betrifft auch den Content. Ich möchte für Designer das Wissen für den visuellen Part eines solchen Prozesses vereinfacht zugänglich machen.

## Zeitplan

Termin | Aufgabe
-- | --
22. 2. 2020 | Diplom-Aufgabe abgeben
04. 4. 2020 | Abgabe eines kurzen Exposés als GitHub-Issue mit Thema/Projekt, Zeitplan sowie Mentoratswunsch. Server-Technologien müssen bis zu diesem Zeitpunkt beantragt werden.
01. 5. 2020 | Themenstruktur des Ratgebers grob erarbeitet.
10.5.2020 | Visualität des Ratgebers erarbeitet.Feedback für grobe Struktur eingeholt bei Experten. (Senden an Experten).
11.5.2020 | Mentorat Feedback für Visualität eingeholt.
15.5.2020 | Themenstruktur nach Feedback von Experten ausgearbeitet.Content zur Abnahme an Experten.
16. 5. 2020 | Review in der Klasse mit externem Dozent.
20. 5. 2020 | Entwickler Umgebung für Review vorbereitet.Content Abnahme durch Experten.
28.5.2020 | Mentorat Feedback Content und Visualität.
29. 5. 2020 | Diverse Kapitel abgefüllt für:Technisches Review durch Alex Jenter.
05.6. 2020 | Review in der Klasse mit Boris Périsset.
08.6.2020 | Mentorat Abschlussgespräch
14. 6. 2020, 8:15 Uhr | Abgabe der Diplom-Arbeit auf ein frei wählbares GitHub-Repository. URL zu Repository & Screenshots aller wesentlichen Teile werden auf GitHub-Issue abgegeben.
26. 6. 2020 | Verteidigung 13:15  – 14:00
Juli & August | Benotung

## Experten für Fachwissen

**Markus Graf** (bestätigt)
Berater für Web Accesibility

**Dr. Andreas Uebelbacher** (folgt)
Leiter Dienstleistungen
Stiftung Zugang für Alle

**Martin Stauch** (bestätigt)
UX-Director
Publicis Schweiz

**Comment by signalwerk** [comment]
@NMA93 gemäss deinem Zeitplan solltest du die struktur des Ratgebers parat haben. Bist du auf Kurs? Konntest du deine Ideen in eine konkrete Richtung lenken und Inhalte daraus ableiten?

 Benötigst du noch infrastruktur?

**Comment by NMA93** [comment]
@signalwerk  Die Struktur steht und wird in den nächsten Tagen mit meinem Mentor verfeinert. Die Richtung konnte ich festlegen und beginne nun schon mit dem Schreiben der Kapitel. Infrastruktur benötige ich keine, mir reicht github für das Hosting.
