### ISSUE TITLE
Exposé Pascale

### ISSUE THREAD

**Issue by pascaleva** [logrinto/IAD2017.diplom#10]
# Exposé Pascale 
## Vorgelegt von
Pascale Anderegg, Dietzingerstrasse 12, 8003 Zürich, pascale.anderegg@gmail.com
## Mentoriert von
Fabian Scheiwiller, Steinberggasse 20, 8400 Winterthur ZH, hallo@fabianscheiwiller.ch	

## Lehrgang
Schule für Gestaltung Zürich, sfgz.ch | Bildungsgang Interaction Design HF | Dipl. Gestalter/-in HF, Kommunikationsdesign mit Vertiefungsrichtung Interaction Design
## Ausgangslage
Wir werden tagtäglich mit den Folgen des Klimawandels konfrontiert. Uns werden aber selten Lösungen präsentiert, die direkt durch unser Handeln beeinflusst werden können. 
Der selbstverständliche Lebensmitteleinkauf beim Grosshändler ist nicht nachhaltig und für eine Person in der Schweiz macht die Ernährung den zweitgrössten Posten bei der Umweltbelastung aus. Dabei führen minimale Änderungen unserer Essgewohnheiten zu grossen Effekten. Es liegt jedoch in den meisten Fällen ganz in der Entscheidung von jedem Einzelnen, was schlussendlich auf dem Teller landet. Die Ansprüche an die Lebensmittelversorgung verändern sich jedoch. Über die Grundversorgung hinaus werden das Vertrauen in regionale Produkte und die Fairness bei der Lebensmittelerzeugung immer wichtiger.

## Ziel dieser Arbeit
In dieser Diplomarbeit möchte ich mit Hilfe des Human Centered Design Prozesses herausfinden wie in der Stadt lebende Personen ihren Lebensmittelkonsum kritisch reflektieren und auf eine vermehrt regionale Ernährung sensibilisiert werden können. Die Arbeitsschritte sowie die gewonnenen Erkenntnisse sollen auf einer Website dokumentiert werden.

## Problemstellung
Der tägliche Lebensmittelkonsum wird zu wenig reflektiert oder Massnahmen ergriffen, diesen zu verändern. Was wir heute über die Herkunft unserer Lebensmittel wissen, hängt häufig davon ab, welche Medien genutzt werden. Vieles davon kann gar nicht mehr selbst erlebt werden, sondern wird medial vermittelt.

## Challenge
Wie können in der Stadt lebende Personen ihren Lebensmittelkonsum bewusster wahrnehmen und auf eine vermehrt regionale Ernährung sensibilisiert werden?

## Zeitplan

| Termin | Aufgabe | 
| -------- | -------- | 
|22.2.2020     | Diplom-Aufgabe abgeben     | | -------- | -------- |  
| 4.4.2020     | Abgabe eines kurzen Exposés als GitHub-Issue mit Thema/Projekt, Zeitplan sowie Mentoratswunsch. Server-Technologien müssen bis zu diesem Zeitpunkt beantragt werden.     | | -------- | -------- | 
| 27.3.2020     | 1. Mentorat (Besprechung Thema, Methodik und Endprodukt)     | 
| 4.4.2020 | Abgabe eines kurzen Exposés als GitHub-Issue mit Thema/Projekt, Zeitplan sowie Mentoratswunsch. Server-Technologien müssen bis zu diesem Zeitpunkt beantragt werden |
| 8.4.2020 | 2. Mentorat (Erkenntnisse Interviews, Umfrage und erste Ideenansätze besprechen) |
| Mitte April | 3. Mentorat (Review Persona, VPC und Idee vertiefen) |
| Anfangs Mai | 4. Mentorat (Review Storyboard der Idee) |
| Mitte Mai | 5. Mentorat (Wireframes, Testing, Wireframes Website anschauen |
| 16.5.2020 |  Review in der Klasse mit externem Dozent |
| vor 29.5.2020 | 6. Mentorat (Entwurf Onepager anschauen, Highfi Design der Lösung)
| 29.5.2020 | Technisches Review durch Alex Jenter |
| 5.6.2020 | Review in der Klasse mit Boris Périsset |
| Mai |	7. Mentorat tbd |
| 14.6.2020 – 8:15 Uhr | Abgabe der Diplom-Arbeit auf ein frei wählbares GitHub-Repository. URL zu Repository & Screenshots aller wesentlichen Teile werden auf GitHub-Issue abgegeben.|
| 26.6.2020 | Verteidigung 15:30 – 16:15|
|Juli & August | Benotung |

**Comment by signalwerk** [comment]
@pascaleva Gemäss deinem Zeitplan solltest du bald deine Idee konkretisiert haben. Dein Exposé war noch sehr offen formuliert und erst eine Stossrichtung. Konntest du in den letzten Wochen deine Idee verfestigen?

Brauchst du noch Infrastruktur von der Schule?

**Comment by pascaleva** [comment]
@signalwerk 
Ich benötige eine Domain für die Diplomarbeit
