### ISSUE TITLE
Exposé Wolfgang

### ISSUE THREAD

**Issue by wschoeck** [logrinto/IAD2017.diplom#11]
## Exposé Diplomarbeit Wolfgang Schoeck
Schule für Gestaltung Zürich 
Dipl. Gestalter/-in HF, Kommunikationsdesign mit Vertiefungsrichtung Interaction Design

Vorgelegt von:
Wolfgang Schoeck

Mentoriert durch:
Armin Egli
Roman Rast

## Thema: Der Quartierladen
Ziel meiner Diplomarbeit ist es, ein digitales Produkt zu entwickeln, welches Läden, die sich in in einer unmittelbaren Wohngegend befinden – sogenannten «Quartierläden – hilft, sich in Zeiten des Onlinehandels und der damit verbundenen Dominanz von grossen Internethändlern, zu behaupten. Dabei soll der Schwerpunkt in erster Linie auf der direkten und schnellen Verfügbarkeit von diversen Produkten sowie auf der Beratung durch das Personal liegen, beides Aspekte, durch die sich ein Quartierladen auf Grund der örtlichen sowie der persönlichen Nähe zum Kunden auszeichnet. Mit dem Angebot verbundene soziale Themen sollen dabei in das Gesamtkonzept mit einfliessen.

## Das Produkt
Bei der Produktentwicklung soll dafür ein Lieferservice mittels Fahrradkurier ausgearbeitet sowie auf Formen der personalisierten Beratung eingegangen werden. Zudem werden Storekonzepte sowie die Organisation von Lagerräumen und Lieferketten analysiert als auch Möglichkeiten für eine extra darauf ausgerichtete Plattform überprüft. Als Endprodukt soll ein Hi-Fi-Prototype einer Website entstehen, welche das Produkt vorstellt und einen typischen Ablauf bei der Nutzung des Angebots aufzeigt.

## Technische Anforderungen
Webserver, Webhosting, Domain Registrierung
MySQL Server (Theoretische Voranmeldung, Verwendung noch nicht konkret)

#### 6. – 12. April
Identify the Problem
Find ideas
Mentorat Armin Egli am 8. April

#### 13. – 19. April
Build and test the idea
Nutzungskontext kennen
Nutzungskontext spezifizieren
Mentorat Roman Rast am 17. April

#### 20. – 26. April
Nutzungskontext spezifizieren
Scope definieren
Vision formulieren
Mentorat Roman Rast am 24. April

#### 27. April – 3. Mai
Ideation
Konzept & Struktur
Mentorat Armin Egli am 30. April

#### 4. Mai – 10. Mai
Lo-Fi-Prototype
Mentorat Roman Rast am 8. Mai

#### 11. Mai – 24. Mai
Hi-Fi-Prototype
Mentorat Roman Rast am 15. Mai

#### 14. Juni
Abgabe der Diplomarbeit

**Comment by signalwerk** [comment]
@wschoeck gemäss deinem Zeitplan solltest du in einem Stadium sein, wo du deine Ideen konkretisieren konntest. Bist du auf Kurs? Ist alles in Ordnung?

Ein PHP/MySQL-Server steht per sofort parat. Komm auf mich zu, wenn du konkret etwas brauchst. Gemäss deiner Beschreibung, warst du ja noch unsicher.

**Comment by wschoeck** [comment]
Hallo Stefan, merci für's erkundigen, das Produkt wird immer konkreter und ich kann demnächst mit der Realisierungs-Phase beginnen. Wird sich bald abzeichnen, ob ich den PHP/MySQL-Server wirklich brauche und ich werde dich informieren, sobald ich das abschätzen kann.
