### ISSUE TITLE
Exposé Nicole

### ISSUE THREAD

**Issue by niciwatri** [logrinto/IAD2017.diplom#12]
## Thema
Transparenz von Lebensmittel Label

## Ausgangslage
Lebensmittel stellen einen zentralen Punkt in unserem Alltag und der Gesellschaft dar. Ökologische und soziale Aspekte werden ein immer wichtigeres Thema für viele Menschen. Bei der heutigen grossen Auswahl an Produkten ist es nicht immer einfach diese Standpunkte zu berücksichtigen. Vorallem, wenn einem nicht nur der Preis sondern auch Inhaltstoffe, Herkunft, Nachhaltigkeit oder Fairness wichtig sind. Es gibt bereits eine Vielzahl an Labels, welche auf den Verpackungen abgebildet sind und Hinweise auf diese Aspekte geben. Eine Vielzahl an Menschen kennen jedoch diese Labels gar nicht und haben keine Motivation sich selbst zu informieren, da es schwierig herauszufinden ist, was genau hinter diesen Labels steckt. Die Transparenz und Seriosität bei den Labels ist ein Problem - es ist nicht einfach nachvollziehbar, welche Standars ein Label erfüllt. Darüber hinaus ist es schwierig, den Überblick über die Anzahl Labels nicht zu verlieren. Das alles erschwert es den Konsummenten, direkt im Laden eine schnelle und faktenbasierte Entscheidung zu treffen.

## Ziel dieser Arbeit
Einen Überblick der Labels in der Schweiz geben, indem alle Infos auf einer Seite verfügbar sind und visuel attraktiv dargestellt werden. Transparenz der Supply Chain ist dabei ein wichtiges Thema, um die Seriosität der Labels aufzuzeigen. Zusätzlich soll man eine Art Ansporn erhalten, um sich überhaupt mit diesen Themen zu beschäftigen. 

Der Sinn ist es, den Leuten eine Plattform zu bieten, auf welcher sie sich informieren und herausfinden können, welche Labels sie wichtig finden und zu den Werten passen, welche sie bereits in anderen Lebenssituationen verfolgen. 

## Zeitplan

|  Datum | Aufgabe| 
| -------- | -------- | 
| 4. 4. 2020     | Abgabe eines kurzen Exposé     | 
| 7. 4. 2020     |   1. Mentoratsgespräch | 
| 11.–15. 4. 2020     |   Interviews führen, um Problemstellung genau zu definieren | 
| 17. 4. 2020     |   Inhalt und Struktur der Webseite erarbeiten | 
| 21. 4. 2020     |   2. Mentoratsgespräch – Review| 
| 28. 4. 2020     |  Erarbeiten von Wireframes | 
| 8. 5. 2020     |   1. Prototyp | 
| 16. 5. 2020     |  Review in der Klasse mit externem Dozent   | 
| 20. 5. 2020     |  3. Mentoratsgespräch | 
| 22. 5. 2020     |   Beginn Code Aufbau Webseite | 
| 29. 5. 2020    |   Technisches Review durch Alex Jenter  | 
| 05. 6. 2020   |  Review in der Klasse mit Boris Périsset   | 
| 14. 6. 2020, 8:15 Uhr   |  Abgabe der Diplom-Arbeit auf ein frei wählbares GitHub-Repository.    | 
| 26. 6. 2020, 09:00 – 09:45    |    Verteidigung | 

### Mentorat durch
Fabian Scheiwiller, hallo@fabianscheiwiller.ch

**Comment by signalwerk** [comment]
@niciwatri Darf ich dich fragen, wie dein Stand ist? Ist soweit alles in Ordnung? Gemäss deinem Plan solltest du bald bei den Wireframes sein. Da du inhaltlich dir wohl viel vorgenommen hast, bist du an infos und relevante daten gekommen?

Brauchst du von der seite der Schule noch etwas? Infrastruktur?
