### ISSUE TITLE
Exposé DA Steffi

### ISSUE THREAD

**Issue by stfffchs** [logrinto/IAD2017.diplom#2]
# Exposé DA Steffi «labels»
## Vorgelegt von
Stephanie Fuchs, Zelgmatt 19, 8627 Grüningen, st.a.fuchs@gmail.com
## Mentoriert von
Fabian Scheiwiller, Steinberggasse 20, 8400 Winterthur ZH, hallo@fabianscheiwiller.ch	
### Weitere Unterstützende
- Roman Rast, Zühlke Engineering AG,  UX und Implementierung
- Christof Elkuch, Mettler Toledo GmbH, Fachwissen Retail SBU Basic Weighing
- Sonja Geissbühler, Coop, Fachwissen Retail
## Lehrgang
Schule für Gestaltung Zürich, sfgz.ch | Bildungsgang Interaction Design HF | Dipl. Gestalter/-in HF, Kommunikationsdesign mit Vertiefungsrichtung Interaction Design
## Ausgangslage
Nachhaltigkeit und Reduzierung von Abfall sind omnipräsent. Viele Retailer bieten deshalb zur Reduzierung von Plastiksäckchen in der Gemüse-/Früchteabteilung wiederverwendbare Veggiebags zum Kauf an. Die Etiketten für die jeweiligen Gemüse/Früchte müssen aber weiterhin pro Gemüse/Früchte ausgedruckt werden. Diese Etiketten verbrauchen einerseits unnötige Ressourcen und sind andererseits eher unpraktisch, da sie überall kleben wo sie nicht sollen (ausser am Veggiebag) und letztendlich im Müll landen.

## Zielsetzung und Erkenntnisinteresse
In dieser Diplomarbeit möchte ich durch Research, Interviews und Testing herausfinden, wie auf diese gedruckten Etiketten verzichtet werden kann und eine Benutzerführung erarbeiten, welche von Kunden als so praktisch empfunden wird, dass sie ein mögliches Endprodukt sofort nutzen würden. 
## Zeitplan

| Daten | Inhalt | 
| -------- | -------- | 
| 1. Menotrat     | Besprechung Idee/Perspektive/Inhalt, Methodik     | 
| 4. 4. 2020 | Abgabe eines kurzen Exposés als GitHub-Issue mit Thema/Projekt, Zeitplan sowie Mentoratswunsch. Server-Technologien müssen bis zu diesem Zeitpunkt beantragt werden |
| April/Mai | 2. Mentorat (Review Interviewfragen), Research, Interviews |
|  | 3. Mentorat (Review Research, Interviews) Persona, Wireframing 1, Testing 1 |
|  | 4. Mentorat (Review Persona, Testing 1) Wireframing 2, Happy Case Scenario |
|  | 5. Mentorat (Review Wireframing 2, Happy Case Scenario), LoFi, Testing 2, Draft Onepager |
| 16. 5. 2020 |  Review in der Klasse mit externem Dozent |
|  | 6. Mentorat – (Review LoFi, Testing 2, Draft Onepager)
| 29. 5. 2020 | Technisches Review durch Alex Jenter |
| 05. 6. 2020 | Review in der Klasse mit Boris Périsset |
| Mai |	7. Mentorat – TBD |
| 14. 6. 2020 – 8:15 Uhr | Abgabe der Diplom-Arbeit auf ein frei wählbares GitHub-Repository. URL zu Repository & Screenshots aller wesentlichen Teile werden auf GitHub-Issue abgegeben.|
| 18. & 26. 6. 2020 | Verteidigung |
|Juli & August | Benotung |

**Comment by signalwerk** [comment]
@stfffchs Du solltest gemäss deinem Zeitplan mitten im Testing sein. Bist du zeitlich auf Kurs? Konntest du deinen Plan weiter verfolgen und dich inhaltlich konkretisieren?

Benötigst du Infrastruktur von der Schule?

**Comment by stfffchs** [comment]
@signalwerk Joah, der plan ist nicht mehr so aktuell. Aber passt soweit. Nein, ich brauche nichts - soweit ich weiss 👍
