### ISSUE TITLE
Exposé Severin

### ISSUE THREAD

**Issue by severinkilchhofer** [logrinto/IAD2017.diplom#3]
# Exposé Diplomarbeit 
von Severin Kilchhofer

## Thema

Online Transparenz im Textilhandel

## Problemstellung

Heutzutage werden viele Textilprodukte online bestellt. Der Bedarf auf Nachhaltige Kleidung und eine transparente Kommunikation der Onlinehändler ist so hoch wie noch nie. Viele Leute informieren sich gerne über den Herstellungsort und die Materialien der Kleider. Im Moment sind diese Informationen Online schwer auffindbar. Im Gegensatz dazu, können Personen heute in Ladengeschäften die Etiketten genau studieren und dort die Produktinformationen entnehmen.

## Ziel der Arbeit

Mein Ziel ist es, einen Service anzubieten, welcher Onlineshopanbietern erlaubt die genauen Herstellerdaten im eigenen Shop anzuzeigen. Dies ermöglicht eine API (Programmierschnittstelle) welche von Herstellern sowie Shopbetreibern eingebunden werden kann. 
Bereits jetzt gibt es eine UPC Nummer, welche auf ein eindeutiges Produkt zeigt. Mit dieser Nummer kann der Shop mittels API an Produktinformationen gelangen und diese anzeigen.

In einer übersichtlichen Webanwendung soll ein interessierter Shop oder Hersteller auf einfache Weise den Service verstehen und die Vorteile für sich einsehen können. 
Ich möchte die Sicht von beiden Parteien (Shopanbieter und Textilhersteller) aufzeigen.
Mit verschiedenen Medientypen werde ich Anwendungsbeispiele visualisieren und beschreiben. Die Benutzerführung wird durch gezielt eingesetzte Animationen unterstützt und soll dadurch den Nutzer besser durch die Webseite begleiten und einbeziehen.

Aufgrund der Aufgabenstellung und dem Umfang dieser Diplomarbeit werde ich die oben erwähnte API nur konzeptionell aufzeigen und nicht implementieren.

## Zeitplan

| Datum      | Task |
| --------   | -------- |
| 01/04/2020 | Recherche und Themenfindung Abgeschlossen
| 04/04/2020 | Abgabe Exposé
| 15/04/2020 | Informationsarchitektur mit wichtigsten Aussagen steht
| 27/04/2020 | Wireframes fertig
| 28/04/2020 | Mentorat mit Michael Scherrer-Kast
| 10/05/2020 | Finales Design steht
| 11/05/2020 | Mentorat mit Michael Scherrer-Kast
| 20/05/2020 | Programmierung MVP fertig
| 31/05/2020 | Programmierung fertig
| 01/06/2020 | Mentorat mit Michael Scherrer-Kast
| 05/06/2020 | Review in der Klasse mit Boris Périsset
| 07/06/2020 | Finales Projekt fertig
| 14/06/2020 | Abgabe der Diplom-Arbeit auf ein frei wählbares GitHub-Repository. URL zu Repository & Screenshots aller wesentlichen Teile werden auf GitHub-Issue abgegeben.
| 18/06/2020 | Verteidigung (08:15 – 09:00)

## Technische Anforderungen

- Webserver für Deployment einer modernen Webapplikation
- Eigene URL für das Diplomprojekt

## Mentoriert von

Michael Scherrer-Kast

## Vorgelegt von

Severin Kilchhofer

## Lehrgang

**Schule für Gestaltung Zürich**

Bildungsgang Interaction Design HF 

Dipl. Gestalter/-in HF, Kommunikationsdesign mit Vertiefungsrichtung Interaction Design

**Comment by signalwerk** [comment]
@severinkilchhofer gemäss deinem Zeitplan solltest du deine Ideen konkrtisiert haben und parat sein um mit deinem Mentorat dich auszutauschen. Bist du auf Kurs? 

Was für einen Webserver möchtest du? Was kann ich dir hochfahren?

**Comment by severinkilchhofer** [comment]
@signalwerk 

Hoi Stefan
Ja ich bin im Zeitplan und habe heute das Mentorat.

Mein Projekt werde ich auf Github Pages hosten. 😉

**Comment by signalwerk** [comment]
👌super. merci für das feedback.
