### ISSUE TITLE
Exposé Marc

### ISSUE THREAD

**Issue by marc-hatt** [logrinto/IAD2017.diplom#4]
Datum: 03.04.2020

**Schule für Gestaltung Zürich**
Bildungsgang Interaction Design HF
Dipl. Gestalter/-in HF, Kommunikationsdesign mit Vertiefungsrichtung Interaction Design

# Exposé Abschlussarbeit HFIAD17

### Mentoriert durch
Noch in Abklärung, Infos folgen

### Vorgelegt von
Marc Hatt
Pestalozzistrasse 24
5242 Birr
marc@email.ch

# Inhalt

## Thema
An interactive guide to Typograpy

## Problemstellung
Gute Typographie wird bei uns Gestalterinnen und Gestaltern als Alleinstellungsmerkmal unserer Zunft vorstanden. Doch was ist gute Typographie? Wenn man sich das WorldWideWeb so ansieht, dann gehen da die Meinungen definitiv auseinander. Gewisse Regeln, um eine gute Lesbarkeit zu gewährleisten und den Betrachter bei seinem Ziel – den Text zu verstehen – zu unterstützen, sind dabei zu beachten. Viele dieser Regeln werden wenig oder gar nicht befolgt, und sorgen so für einen Wildwuchs in der Gestaltungswelt des «WWW».

## Ziel dieser Arbeit
Es soll ein Behelf erstellt werden, in dem das Wissen aus Jahrzehnten der Typographie und des Typedesigns herangezogen werden. Eine Sammlung geballten Typographie-Wissens, auf die zurückgegriffen werden kann, um die Qualität eines Projektes, einer Gestaltung auf ein neues Level zu führen. Es soll am Schluss ein Tool geben, dass über die Abschlussarbeit hinaus noch Benutzung finden kann – das ist Ziel Nummer 1.

## Persönliches Interesse
Als UX-Designer ist mir die User-Journey eines jeden Benutzers sehr wichtig. Gute Hierarchien, die richtigen Farben, das perfekte Erlebnis, fängt bei mir bei der Schriftwahl und dem durchsetzen typographischer Grundsätze an. Ich interessiere mich sehr für Schrift, ihre Form und ihre Benutzung, und so will ich dieses Interesse in meiner Abschlussarbeit zum Ausdruck bringen.

## Vorläufige grobe Themenstruktur

- Interpunktion (Satzzeichen) und Styling
- Textkörper (Grundtext)
- Lesbarkeit
- Hierarchie und Layout-Architektur
- Schriftwahl und Schriftmischung

# Technische Anforderungen
## Server
Standard Webserver mit PHP-Funktionalität zum Aufsetzen eines CMS.

## CMS
Wordpress 5.X

# Zeitplan

Termin | Aufgabe
-- | --
22. 2. 2020 | Diplom-Aufgabe abgeben
04. 4. 2020 | Abgabe eines kurzen Exposés als GitHub-Issue mit Thema/Projekt, Zeitplan sowie Mentoratswunsch. Server-Technologien müssen bis zu diesem Zeitpunkt beantragt werden.
01. 5. 2020 | Informationsarchitektur und Themenfelder stehen
12.5.2020 | Erste Designspezifikationen stehen, Wissen ist zum Grossteil zusammengetragen und sortiert
15.5.2020 | Feedback zu Design und Inhalt einholen
22. 5. 2020 | Feedback ist umgesetzt
28.5.2020 | erneut Feedback zu Design und Inhalt einholen
29. 5. 2020 | Struktur ist technisch umgesetzt, gewisser Content ist abgefüllt. Technisches Review durch Alex Jenter.
05.6. 2020 | Review in der Klasse mit Boris Périsset.
08.6.2020 | Mentorat Abschlussgespräch
14. 6. 2020, 8:15 Uhr | Abgabe der Diplom-Arbeit auf ein frei wählbares GitHub-Repository. URL zu Repository & Screenshots aller wesentlichen Teile werden auf GitHub-Issue abgegeben.
18. 6. 2020 | Verteidigung vor Experten des Bundes und Jury 
Juli & August | Benotung

**Comment by signalwerk** [comment]
@marc-hatt gemäss deinem Zeitplan solltest du bald mit deinem Inhalt soweit sein, dass du dies an externe weiter zeigen kannst. Bist du im Zeitplan? Konntest du deine Inhalte finden und dich auf eine spannende Auswahl beschränken?

Benötigst du noch Infrastruktur von der Schule?

**Comment by marc-hatt** [comment]
@signalwerk  Sali Stefan

Ich bin soweit im Zeitplan, dass ich passende Inhalte finden konnte und meine Informationsarchitektur sollte ebenfalls gemäss Zeitplan fertig werden. Es war allerdings weitaus schwerer, an Material zu kommen, welches NICHT aus dem Internet stammt. Weiter zeigen konnte ich es bisher nur Betriebs-Intern, da ich bisher noch keinen Mentor finden konnte… leider.

Bisher läuft das Development lokal und später werde ich es auf eine Subdomain meines Hostings packen. Da ich dafür eh schon bezahle. Ich brauche also erst Infrastruktur für den vollen, offiziellen Launch.
