### ISSUE TITLE
Exposé Natasha

### ISSUE THREAD

**Issue by natasharuf** [logrinto/IAD2017.diplom#5]
<h1>EXPOSÉ – «Interaktive Geschichte von Gehörlosen» </h1>

<br>

<h2>Ausgangslage | Idee</h2>

Viele wissen nichts über die Geschichten von bekannten oder berühmten Gehörlosen. Ein Beispiel ist Thomas Alva Edison. Er war der Erfinder der Glühlampe, hatte bereits in seiner Kindheit Hörprobleme und war sein Leben lang schwerhörig. Solche und viele andere  interessante Lebensgeschichte werden oft vergessen. Damit man sich an diese Geschichten wieder erinnert, erstelle ich eine Webseite mit einer interaktiven Zeitlinie, auf der die Geschichten von bekannten und berühmten gehörlosen Menschen gelesen und angeschaut werden können.  

<h2>Konzept</h2> 

Die interaktives Zeitlinie ist heutzutage eine beliebt für geschichtliche Themen. Auf der Zeitlinie  werden Bilder, Videos, Texte, 3D im Browser und eventuell Games eingebaut. Die einzelnen Elemente werden nach Jahrgang und alphabetisch sortiert. Die Zeitlinie kann laufend mit neuen Geschichten ergänzt werden. 

Die Webseite möchte ich ähnlich wie das interaktive Projekt von Datyell Close aufbauen. Bei Datyell werde ich nach einer Vorlage einer solchen interaktive Zeitlinie fragen. Falls ich von ihnen nichts erhalte,  suche ich im Internet ein ähnliche Vorlage für mein Projekt. 

<h3>Font</h3>
Die Fonts werden mit «Roboto» angewendet und bei der Schriftgrösse wird auf Lesbarkeit geachtet.

<h3>Gestaltung</h3>
Die Darstellung auf der Website wird mit responsivem Design gestaltet und auch die Usability wird berücksichtigt.

<h2>Ausstellung</h2>

Die interaktive Zeitlinie wird auf einem Tablet präsentiert. Die Leute können die Zeitlinie und deren Inhalte selber bedienen, lesen und anschauen. Es wird ein Interface zwischen User und Tablet geben. 

<h2>Vorgehen</h2>

1. Helfer (Patrick Mock) für das Sammeln der Geschichten  finden
2. Tutor/in und Mentor/in finden
3. Konzept erstellen
4. Vorlage in Code für eine interaktive Zeitlinie finden, kaufen und programmieren
5. Informationen aus Büchern, Artikeln, Internetquellen  und anderen Quellen sammeln
6. Die Medien in die interaktive Zeitlinie einbauen
7. Testperson finden und Human Centered Design durchführen
8. Kritik, Tipps und Korrekturen aufnehmen und einbauen

<h2>Zeitplan</h2>
<table>
<tr><td><b>Daten</b></td><td><b>Task</b></td></tr>
<tr><td>04.04</td><td>Abgabe eines kurzen Exposés auf Git-Issue mit Mentoratswunsch</td></tr>
<tr><td>27.04</td><td>Die aktuelle Diplomarbeit mit Mentor besprechen und verbessern</td></tr>
<tr><td>01.05</td><td>1. Version des Konzepts für Dipl.-Arbeit an Tutorin geben und korrigieren lassen</td></tr>
<tr><td>08.05</td><td>Die aktuelle Diplomarbeit mit Mentor besprechen und verbessern</td></tr>
<tr><td>16.05</td><td>Review in der Klasse mit externem Dozent</td></tr>
<tr><td>19.05</td><td>2. Version des Konzepts derDipl.-Arbeit an Tutorin geben und korrigieren lassen</td></tr>
<tr><td>25.05</td><td>Die aktuelle Diplomarbeit mit Mentor besprechen und verbessern</td></tr>
<tr><td>29.05</td><td>Technisches Review durch Alex Jenter</td></tr>
<tr><td>09.06</td><td>Die aktuelle Diplomarbeit mit Mentor besprechen und verbessern</td></tr>
<tr><td>13.06</td><td>Abgabe der Diplomarbeit auf Git-Repository</td></tr>
<tr><td>18.06</td><td>Verteidigung der Diplomarbeit</td></tr>
</table>

<h2>Mentor & Tutorin</h2>

- 	Malte Spielberger (Mentor)
- 	Sarah Guidi (Tutorin)

<h2>Verfasserin</h2>

Natasha Ruf, 6. Semester in Interaction Design HF beim SFGZ
Mail natasha.ruf@gmail.com
Whatsapp 0797030544

Quellen von Diplomarbeit – https://signalwerk.github.io/IAD.LAB.DOC/diplom/

**Comment by signalwerk** [comment]
@natasharuf gemäss deiner Timeline solltest du bald mit einer ersten Version von deine Konzept parat sein. Bist du auf Kurs? Konntest du die Inhalte recherchieren und entsprechend anreichern?

Brauchst du noch zusätzliche Infrastruktur von der Schule?

**Comment by natasharuf** [comment]
@signalwerk, Danke für dein Aufmerksamekeit. =)

Die technische Umsetzung läuft bis jetzt gut und habe bereits das Domain gekauft. Die Inhalte wurde ab und zu zu mir geliefert. Das Konzept wird bald fertig sein und die Organisation mit Tutorin läuft auch gut. Die Timeline mit Mentor ist momentan mehr agil. 

Nein, ich brauche momentan kein zusätzliche Infrastruktur von der Schule.
