### ISSUE TITLE
Exposé Lars

### ISSUE THREAD

**Issue by larsmaeder** [logrinto/IAD2017.diplom#6]
Datum: 03.04.2020

**Schule für Gestaltung Zürich** 
Bildungsgang Interaction Design HF 
Dipl. Gestalter/-in HF, Kommunikationsdesign mit Vertiefungsrichtung Interaction Design

# Exposé Diplomarbeit

## Mentoring durch 

**Patrick Kaspar**
Lithop Electronic Media AG

## Vorgelegt von
 
**Lars Mäder**
Zürichstrasse 8
8610 Uster
mail@larsmaeder.ch

# Inhaltsverzeichnis Exposé

1. Problemstellung
2. Zielsetzung und Erkenntnisinteresse
3. Zeitplan

# Problemstellung

Das Aufkommen von Voice User Interfaces (VUIs) wie Amazon Alexa, Google Assistant usw. ist eine grosse Veränderung in der Mensch-Computer-Interaktion. Das Entwerfen von Voice-User-Interfaces (VUI) unterscheidet sich deutlich vom Entwerfen von Apps für grafische Benutzeroberflächen (GUI). Daraus ergibt sich eine upcoming Challenge für UI-/UX-Designer. Anbieter von Sprachassistenten bieten bereits eigene Guidelines an, doch bewegen sich diese meistens nur auf technischer Ebene und sind deshalb nur für Entwickler geeignet. Aber wie gestalten nun Designer solche VUIs, damit diese in der Nutzerführung sowie auch visuell optimal funktionieren? In herkömmlichen GUIs navigieren die Benutzer per Finger (Touch) mittels visuell sichtbaren Bedienelemente innerhalb einer App. Die Benutzer sehen, wann sie einen neuen Abschnitt oder eine neue Benutzeroberfläche öffnen. In VUIs werden die Finger zum Mund. Die Benutzer navigieren über Sprachinput und werden gleichzeitig über Sprachfeedback geführt.

# Zielsetzung und Erkenntnisinteresse

Um eine effektive und intuitive User Experience zu garantieren, ist es deshalb wichtig die Benutzer nicht alleinig über Sprache zu führen, sondern diese zusätzlich mittels visuellem Feedback zu unterstützen. VUIs sollten so gestaltet werden, dass sie sich an die vielfältigen Möglichkeiten anpassen können, mit denen Benutzer Bedeutung und Absicht durch Sprache ausdrücken. Die Benutzer sollten jederzeit wissen, wo sie sich befinden und welche Funktionen Sie gerade verwenden. Das Ziel dieser Arbeit ist deshalb eine Übersicht und Guide zu erstellen, um so einen Leitfaden für die Gestaltung von VUIs zu bilden. Dieser soll unter anderem bekannte Probleme, wie z.B. Visual-/Voice-Feedback und Nutzerführung eines VUIs aufzeigen und mögliche Lösungsvorschläge für Designer anbieten. Der Leitfaden soll sich mittels visuellen und akustischen Beispielen sowie Interaktivität von bestehenden Tech-/Developer-Guides abheben.

# Zeitplan

| Zeit | Task |
| --------- | --------- |
| 22. 2. 2020 | Diplom-Aufgabe abgeben |
| 4. 4. 2020 | Abgabe eines kurzen Exposés als [GitHub-Issue](https://github.com/logrinto/IAD2017.diplom/issues) mit Thema/Projekt, Zeitplan sowie Mentoratswunsch. Server-Technologien müssen bis zu diesem Zeitpunkt beantragt werden. |
| 16. 4. 2020 | Seitenstruktur, Interaktionen und Themenbereiche definiert. |
| 1. 5. 2020 | Mind. 2/3 der Inhalte sind geschrieben. |
| 8. 5. 2020 | Visualität erarbeitet. |
| 15. 5. 2020 | Mentorat Zwischenbesprechung |
| 16. 5. 2020 | Review in der Klasse mit externem Dozent |
| 22. 5. 2020 | Restliche Inhalte geschrieben und bereit zum abfüllen. |
| 28. 5. 2020 | Development environment final und first push |
| 29. 5. 2020 | Technisches Review durch Alex Jenter |
| 15. 5. 2020 | Mentorat Zwischenbesprechung |
| 05. 6. 2020 | Review in der Klasse mit Boris Périsset |
| 15. 6. 2020 | Mentorat finales Feedback |
| 14. 6. 2020, 8:15 Uhr | Abgabe der Diplom-Arbeit auf ein frei wählbares GitHub-Repository. URL zu Repository & Screenshots aller wesentlichen Teile werden auf [GitHub-Issue](https://github.com/logrinto/IAD2017.diplom/issues) abgegeben. |
| 26. 6. 2020 | Verteidigung, 14:00–14:45 |
| Juli & August | Benotung |

**Comment by signalwerk** [comment]
@larsmaeder gemäss deinem Zeitplan solltest du mehrheitlich fertig sein beim erstellen deiner Inhalte. Bist du auf Kurs? Konntest du relevante Quellen finden und dies entsprechend integrieren?

Benötigst du noch Server-Infrastruktur von der Schule?

**Comment by larsmaeder** [comment]
@signalwerk Ich habe meinen Zeitplan ein bisschen umgestaltet und die technische Umsetzung nach vorne genommen. Aktuell bin ich meinen Seitenaufbau und die inhaltlichen Strukturen am festlegen. Quellen konnte ich einige finden, welche ein gutes Fundament für meine Arbeit bieten. Fragen werde ich wahrscheinlich noch bei Alex bzw. beim technischen Review haben, alles in allem bin ich auf Kurs.

Server-Infrastruktur werde ich keine benötigen.
