### ISSUE TITLE
Exposé Matthias

### ISSUE THREAD

**Issue by matthiasmeierkoch** [logrinto/IAD2017.diplom#7]
Datum: 30.03.2020
Bildungseinrichtung: Schule für Gestaltung Zürich
Bildungsgang: Dipl. Gestalter/-in HF, Kommunikationsdesign mit Vertiefungsrichtung Interaction Design

## Vorgelegt von:
Matthias Koch
Zurlindenstrasse 47 
8003 Zürich

## Mentoring durch
Richard Zimmermann

### Weitere Unterstützende:
* James Christensen - Full Stack Developer

## Ausgangslage:
Zwischen 2006 und 2016 sind zwischen 41000 und 46000 Personen im Jahr nach Zürich gezogen. Der grösste Teil der Zuwanderer sind Ausländer. 

> Quelle: [Tagesanzeiger - Die grosse Zürcher Zuwandererstatistik](https://www.tagesanzeiger.ch/zuerich/stadt/die-grosse-zuercher-zuwanderungsstatistik/story/18344973)

Für viele ist ein Kantonswechsel und besonders ein Landeswechsel mit einer Unsicherheiten verbunden. Wo melde ich mich an? Wie entsorge ich meinen Abfall richtig? wie stehen öffentliche Parkplätze zur verfügung? oder wo kann ich mich sportlich betätigen?
Zudem erfreut man sich darüber sein neues Quartier zu entdecken und möchte einige Tipps und mehr über das neue Quartier erfahren.

## Ziel meiner Diplomarbeit:
In meiner Diplomarbeit erarbeite ich eine Webseite welche Informationen, Adressen und Links für Zuwanderer nach Zürich Wiedikon bietet. Zusätzlich zu den wichtigsten Richtlinien geben Infografiken und Kartenvisualisierungen Tipps, Tricks und Informationen zum Quartierleben.

## Persönlicher Bezug:
Ich habe einen persönlichen Bezug zu dem Thema da ich im April 2020 von Zug nach Zürich umgezogen bin. Daher kommen zur Zeit immer wider an Situationen in meinem Alltag auf in denen ich von einen Solchen «Quartier-Guide» profitieren könnte.

## Zeitplan: 
Datum | Task
-- | --
01/04/2020 | Recherche und Themenfindung
04/04/2020 | Abgabe Exposé
15/04/2020 | Eingrenzung der Arbeit und Inhaltsarchitektur
27/04/2020 | Wireframes
28/04/2020 | Besprechung mit dem Mentor
10/05/2020 | Design fertig
11/05/2020 | Besprechung mit dem Mentor
20/05/2020 | 80% Der Seiten sind umgesetzt
31/05/2020 | Umsetztung Abschliessen
01/06/2020 | Letzte Besprechung mit dem Mentor
05/06/2020 | Review in der Klasse mit Boris Périsset
07/06/2020 | Fertigstellung des Projekt
14/06/2020 | Abgabe der Diplom-Arbeit auf ein frei wählbares GitHub-Repository. URL zu Repository & Screenshots aller wesentlichen Teile werden auf GitHub-Issue abgegeben.
18/06/2020 | Verteidigung (08:15 – 09:00)

## Ressourcen
* Datensätze von Open Data Zürich
* Webserver für das Veröffentlichen einer Modernen Webseite / Webapplikation
* Eine Domain für die Diplomarbeit

**Comment by signalwerk** [comment]
@matthiasmeierkoch Ich hatte von Richard Zimmermann noch eine Anfrage erhalten betreffend deinem Mentorat. Ich habe seine Fragen in der Zwischenzeit (spät) beantwortet und hoffe, ihr seit bereits im Austausch. Gemäss deinem Zeitplan solltest du bei den Wireframes sein. Bist du auf kurs? Konntest du dich inhaltlich vertiefen?

Du schreibst, dass du einen Webserver zur Veröffentlichung brauchst. Kannst du mir sagen, was du genau von der Schule für Infrastruktur brauchst. PHP/MySQL-Server stehen parat.

**Comment by matthiasmeierkoch** [comment]
Hallo @signalwerk Ich habe heute seine definitive zusage bekommen. Ich bin weiterhin dabei mich inhaltlich auseinanderzusetzten und an der erarbeitung der Wireframes.

Für die veröffentlichung der Webseite und das hosten der ensprechenden resourcen sollte mir ein Github webserver ausreichen.
