### ISSUE TITLE
Exposé Marius

### ISSUE THREAD

**Issue by mariusbecker** [logrinto/IAD2017.diplom#8]
Datum: 04.04.2020
Bildungseinrichtung: Schule für Gestaltung Zürich
Bildungsgang: Dipl. Gestalter/-in HF, Kommunikationsdesign mit Vertiefungsrichtung Interaction Design

# Vorgelegt von:
Marius Becker
Wohllebgasse 11
8001 Zürich

# Mentoring durch:
tba

## Weitere Unterstützende:
* Isabelle Gerstler – Gärtnerin / Phytotherapeutin

# Ausgangslage:
Viele Menschen aus meinem Bekanntenkreis haben Pflanzen zuhause. Weil sie schön sind, weil sie nützlich sind, wegen Karma, weil sie Leben in die Wohnung bringen, weil grün eine schöne Farbe ist etc. Doch viele dieser Menschen teilen ein gemeinsames Problem: Die Pflanzen sterben ständig. Das Internet bietet zwar viel Fachwissen um diese zu retten, jedoch ist damit stundenlange Recherche in unzähligen Foren verbunden, welche mit unnützem Halbwissen voll sind. 

# Ziel meiner Diplomarbeit:
Schon seit längerem habe ich die Idee eines Pflanzennotrufes (www.pflanzennotruf.ch habe ich schon länger reserviert). Dieser soll als Vermittlungsplattform zwischen Leuten, welche mit sterbenden Pflanzen zu kämpfen haben und Leuten, welche wissen was Pflanzen zum Leben brauchen dienen, und auch über interaktive Step-by-Step anleitungen zum Unterhalt, Umtopfungen, Vermehrungen und Weiterem verfügen. In der Diplomarbeit wird es mir wahrscheinlich nicht möglich sein eine funktionierende Vermittlungsplattform bereit zu stellen, jedoch will ich das Konzept, den Aufbau und die Umsetzung so dokumentieren, dass eine konkrete Umsetzung möglich ist. Veranschaulicht soll soll das surch einen Prorotypen werden. 

# Mein persönlicher Bezug:
Ich habe auch Pflanzen zuhause, habe jedoch das Glück, tatkräftige Unterstützung einer Gärtnerin zu geniessen.  

# Zeitplan
Datum | Task
------------|------------
01/04/2020 | Recherche und Themenfindung
04/04/2020 | Abgabe Exposé
15/04/2020 | Eingrenzung der Arbeit und Inhaltsarchitektur
27/04/2020 | Wireframes
28/04/2020 | Besprechung mit dem Mentor
10/05/2020 | Design fertig
11/05/2020 | Besprechung mit dem Mentor
20/05/2020 | 80% Der Seiten sind umgesetzt
31/05/2020 | Umsetztung Abschliessen
01/06/2020 | Letzte Besprechung mit dem Mentor
05/06/2020 | Review in der Klasse mit Boris Périsset
07/06/2020 | Fertigstellung des Projekt
14/06/2020 | Abgabe der Diplom-Arbeit auf ein frei wählbares GitHub-Repository. URL zu Repository & Screenshots aller wesentlichen Teile werden auf GitHub-Issue abgegeben.
18/06/2020 | Verteidigung (08:15 – 09:00)

**Comment by signalwerk** [comment]
@mariusbecker gemäss deinem Zeitplan solltest du im Wireframe-Stadium sein. Bist du auf kurs? Konnstest du deine Idee in eine Konkrete Bahn leiten? 

Wie steht es mit deinem Mentorat. Bitte mach von diesem Angebot gebrauch.

**Comment by signalwerk** [comment]
Brauchst du noch Infrastruktur (Server, ...) von der Schule?
