### ISSUE TITLE
Exposé Tiö

### ISSUE THREAD

**Issue by tioemayer** [logrinto/IAD2017.diplom#9]
#  Exposé Diplomarbeit Tieu Khe Mayer
Schule für Gestaltung Zürich
Dipl. Gestalter/-in HF, Kommunikationsdesign mit Vertiefungsrichtung Interaction Design

### Vorgelegt von
Tieu Khe Mayer, tieukhe.mayer@gmail.com

### Mentoriert durch
Roman Rast, roman.rast@zuehlke.com

## Thema
Nachhaltiger Konsum

## Problemstellung
Heute gibt es viele Gründe umweltfreundlicher zu konsumieren. In der Stadt Zürich gibt es bestimmt Lebensmittelgeschäfte wo man plastikfrei einkaufen kann. Aber wo sind die? Welche Restaurants unterstützen die plastikfreie Konsumkultur? Wo bekommt man Fairtrade-Produkte? 

Eine Studie des WWF Schweiz aus dem Jahr 2018 zeigt: Neun von zehn Schweizerinnen und Schweizern denken darüber nach, ihren Konsum zu reduzieren. Dennoch wird weiterhin auf Rekordniveau konsumiert. Warum ist das so? Wo liegt die Hemmschwelle? 

Menschen sind Gewohnheitstiere. Die meisten Menschen haben Angst, zu viele umständliche Anpassungen vornehmen zu müssen. Dabei sind es die kleinen Dinge die den längerfristigen Unterschied machen und so zu einem bewussten Entscheid für einen nachhaltigen Lebensstil beitragen. Doch zu diesem ersten Schritt ist es meist ein langer Weg.

## Ziel der Arbeit
Das Ziel meiner Arbeit ist es eine Community Plattform zu konzipieren, die Konsumentinnen und Konsumenten die einen umweltfreundlichen Lebensstil anstreben, sensibilisiert und sie bei der Umsetzung unterstützt.

Dabei soll die Plattform vor allem
- motivieren einen plastikfreien Lebensstil anzustreben
- die Mitglieder der Plattform untereinander inspirieren
- die Konsumentinnen und Konsumenten mit den aktuellen Anbietern vernetzten
- die Mitglieder bei der nachhaltigen Veränderung ihres Lebensstils unterstützen

Durch ein gemeinsam gestartetes Experiment in der Stadt Zürich, das einen Monat andauert, wird der Einstieg in einen plastikfreien Lebensstil für die Mitglieder vereinfacht. Der Startschuss wird ein Workshop sein, an dem sich die Mitglieder treffen und austauschen können. Während des Experiments wird es weitere Veranstaltungen geben. Die Plattform soll nach dem Ende des Experiments weiterleben. Dies sollte anhand von Gamification-Ansätze auf der Plattform erreicht werden.

Aufgrund des Umfangs der Diplomarbeit wird das Experiment nur konzeptionell erarbeitet. 

## Zeitplan
| Daten | Aufgaben |
| --- | --- |
| 04.04.2020 | Abgabe Exposé |
| 10.04.2020 | Umfrage nach Bedürfnissen fertig |
| 17.04.2020 | Seitenstruktur, Inhalte definiert |
| 24.04.2020 | Wireframes fertig |
| 28.04.2020 | Mentorat mit Roman Rast |
| 05.05.2020 | Design für Plattform fertig |
| 09.05.2020 | 1. Teil der Inhalte für Website geschrieben, abfüllen |
| 10.05.2020 | Feedback zum Design eingeholt vom Mentor |
| 16.05.2020 | Review in Klasse mit externen Dozent |
| 20.05.2020 | Design überarbeitet, fertig |
| 27.05.2020 | 2. Teil der Inhalte für Website geschrieben, fertig abgefüllt |
| 03.06.2020 | Mentorat mit Roman Rast |
| 05.06.2020 | Review in der Klasse mit Boris Périsset |
| 07.06.2020 | Finales Projekt fertig |
| 14.06.2020 | Abgabe der Diplom-Arbeit auf ein frei wählbares GitHub-Repository. URL zu Repository & Screenshots aller wesentlichen Teile werden auf GitHub-Issue abgegeben. |
| 26.06.2020 | Verteidigung (11:15 – 12:00) |

**Comment by signalwerk** [comment]
@tioemayer du solltest gemäss deinem Zeitplan soweit sein, dass deine Ideen in erste Wireframes gmündet sind. Konntest du eine Stossrichtung festlegen? Bist du auf kurs? 

Brauchst du noch infrastruktur von der Schule?
